### PR TITLE
Changed links into yum commands

### PR DESCRIPTION
**Pull request by FancyFane**
For ease of use I've converted the links to copy and paste-able yum commands. This should make it easier to get started with the IUS repos.

### CODE REVIEW

**Comment by carlwgeorge** [comment]
Those yum commands for EL5 won't work.  EL5's old version of yum is not smart enough to install from a URL.  Which approach would be cleaner and more efficient?
- have every code block include separate wget and yum commands
- have the EL5 code blocks have separate wget and yum commands, but leave EL6 and EL7 blocks with a single `yum install $URL` line (correct but visually inconsistent IMO)
- leave it as just plain URLs and let the admin decide whether to use wget+yum or just yum

**Comment by carlwgeorge** [comment]
Hey @FancyFane, not sure if you are still interested in this issue or not.  One option might be to just wait until EL5 is EOL, which is like the second option I mentioned, but without the visual inconsistencies.

**Comment by carlwgeorge** [comment]
@FancyFane EL5 is EOL now, would you like to rebase this pull request?

**Comment by sas977** [comment]
Ship:it

**Comment by b-harper** [comment]
I am clearing out stale issues and close them.  If this Pull Request gets updated, we will open it again.

**Pull request closed without merging**
